title: 彼岸
description: Personal knowledge base and blog
cover_image: https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1574&q=80
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
