title: 彼岸
description: Personal blog
theme: minima
header_pages:
  - about.md
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
